version: '3.8'

services:
  node1:
    build: .
    network_mode: "host"
    restart: always
    stdin_open: true
    tty: true
    command: ["1"]

  node2:
    build: .
    network_mode: "host"
    restart: always
    stdin_open: true
    tty: true
    command: ["2"]

  node3:
    build: .
    network_mode: "host"
    restart: always
    stdin_open: true
    tty: true
    command: ["3"]

  node4:
    build: .
    network_mode: "host"
    restart: always
    stdin_open: true
    tty: true
    command: ["4"]